name: climate4R
channels:
  - santandermetgroup
  - conda-forge
  - r
  - defaults
dependencies:
  - climate4r=1.5.1
  - r-irkernel
  - jupyter
  # extra
  - r-devtools
  - r-gridextra
  - r-xtable
  - r-magrittr
  - r-httr
  - r-lattice
  - r-latticeExtra
